/**
 * Exam paper data (static, offline-first).
 *
 * AUTO-GENERATED by `scripts/fetch-exams/` — DO NOT EDIT BY HAND.
 * Re-generate with: `npm run fetch-exams` (default --source=fixture).
 * The UI must import only from `./index.ts`, never this file directly.
 */

import type { ExamPaper } from '$lib/types/exam';

export const papers: ExamPaper[] = [
  {
    "id": "n5-fixture-1",
    "level": "N5",
    "title": "N5 — Đề luyện mẫu A (fixture)",
    "source": {
      "name": "Smart Quiz fixtures (original)",
      "license": "original",
      "fetchedAt": "2026-06-21"
    },
    "durationMinutes": 25,
    "sections": [
      {
        "type": "vocab",
        "title": "語彙 (Từ vựng)",
        "instructions": "Chọn đáp án đúng.",
        "questions": [
          {
            "id": "n5-fixture-1-s1-q1",
            "prompt": "「ねこ」 は えいご で なん ですか。",
            "options": [
              "dog",
              "cat",
              "bird",
              "fish"
            ],
            "answerIndex": 1,
            "explanation": "ねこ = cat (con mèo)."
          },
          {
            "id": "n5-fixture-1-s1-q2",
            "prompt": "「いぬ」 の いみ は どれ ですか。",
            "options": [
              "mèo",
              "chó",
              "chim",
              "cá"
            ],
            "answerIndex": 1,
            "explanation": "いぬ = con chó."
          }
        ]
      },
      {
        "type": "grammar",
        "title": "文法 (Ngữ pháp)",
        "instructions": "Chọn trợ từ/từ điền vào chỗ trống.",
        "questions": [
          {
            "id": "n5-fixture-1-s2-q1",
            "prompt": "これ ____ ほん です。",
            "options": [
              "は",
              "を",
              "に",
              "の"
            ],
            "answerIndex": 0,
            "explanation": "は đánh dấu chủ đề: \"Đây là sách\"."
          },
          {
            "id": "n5-fixture-1-s2-q2",
            "prompt": "わたし は がくせい ____。",
            "options": [
              "です",
              "ます",
              "ない",
              "たい"
            ],
            "answerIndex": 0,
            "explanation": "Danh từ + です: \"Tôi là học sinh\"."
          }
        ]
      },
      {
        "type": "reading",
        "title": "読解 (Đọc hiểu)",
        "instructions": "Đọc đoạn văn và trả lời.",
        "passages": [
          {
            "id": "n5-fixture-1-s3-p1",
            "text": "たなかさん は にほんじん です。とうきょう に すんで います。まいにち でんしゃ で かいしゃ に いきます。",
            "translation": "Anh Tanaka là người Nhật. Sống ở Tokyo. Mỗi ngày đi tàu điện đến công ty."
          }
        ],
        "questions": [
          {
            "id": "n5-fixture-1-s3-q1",
            "prompt": "たなかさん は どこ に すんで いますか。",
            "options": [
              "おおさか",
              "とうきょう",
              "きょうと",
              "なごや"
            ],
            "answerIndex": 1,
            "passageId": "n5-fixture-1-s3-p1",
            "explanation": "「とうきょう に すんで います」."
          },
          {
            "id": "n5-fixture-1-s3-q2",
            "prompt": "たなかさん は なに で かいしゃ に いきますか。",
            "options": [
              "バス",
              "でんしゃ",
              "くるま",
              "じてんしゃ"
            ],
            "answerIndex": 1,
            "passageId": "n5-fixture-1-s3-p1",
            "explanation": "「でんしゃ で … いきます」."
          }
        ]
      }
    ]
  },
  {
    "id": "n5-sample-1",
    "level": "N5",
    "title": "N5 — Đề mẫu 1",
    "source": {
      "name": "Smart Quiz (original sample)",
      "license": "original",
      "fetchedAt": "2026-06-21"
    },
    "durationMinutes": 30,
    "sections": [
      {
        "type": "vocab",
        "title": "語彙 (Từ vựng)",
        "instructions": "Chọn cách đọc/nghĩa đúng.",
        "questions": [
          {
            "id": "n5s1-v1",
            "prompt": "がっこう の よみかた は どれ ですか。",
            "options": [
              "がっこう",
              "がくこう",
              "かっこう",
              "がっごう"
            ],
            "answerIndex": 0,
            "explanation": "学校 (がっこう) = trường học."
          },
          {
            "id": "n5s1-v2",
            "prompt": "「みず」 の かんじ は どれ ですか。",
            "options": [
              "火",
              "水",
              "木",
              "土"
            ],
            "answerIndex": 1,
            "explanation": "水 (みず) = nước."
          }
        ]
      },
      {
        "type": "grammar",
        "title": "文法 (Ngữ pháp)",
        "instructions": "Chọn từ điền vào chỗ trống.",
        "questions": [
          {
            "id": "n5s1-g1",
            "prompt": "わたし ____ がくせい です。",
            "options": [
              "は",
              "を",
              "に",
              "へ"
            ],
            "answerIndex": 0,
            "explanation": "は đánh dấu chủ đề: \"Tôi là học sinh\"."
          },
          {
            "id": "n5s1-g2",
            "prompt": "まいにち がっこう ____ いきます。",
            "options": [
              "で",
              "を",
              "へ",
              "が"
            ],
            "answerIndex": 2,
            "explanation": "へ chỉ hướng di chuyển: \"đi đến trường\"."
          }
        ]
      },
      {
        "type": "reading",
        "title": "読解 (Đọc hiểu)",
        "instructions": "Đọc đoạn văn và trả lời câu hỏi.",
        "passages": [
          {
            "id": "n5s1-p1",
            "text": "わたし は まいあさ ６じ に おきます。あさごはん を たべて、７じ に うち を でます。がっこう まで バス で いきます。",
            "translation": "Tôi thức dậy lúc 6 giờ mỗi sáng. Ăn sáng xong, 7 giờ rời nhà. Tôi đi bus đến trường."
          }
        ],
        "questions": [
          {
            "id": "n5s1-r1",
            "prompt": "この ひと は なんじ に おきますか。",
            "options": [
              "６じ",
              "７じ",
              "８じ",
              "９じ"
            ],
            "answerIndex": 0,
            "passageId": "n5s1-p1",
            "explanation": "「６じ に おきます」."
          },
          {
            "id": "n5s1-r2",
            "prompt": "がっこう まで なに で いきますか。",
            "options": [
              "でんしゃ",
              "バス",
              "じてんしゃ",
              "あるいて"
            ],
            "answerIndex": 1,
            "passageId": "n5s1-p1",
            "explanation": "「バス で いきます」."
          }
        ]
      }
    ]
  },
  {
    "id": "n4-fixture-1",
    "level": "N4",
    "title": "N4 — Đề luyện mẫu A (fixture)",
    "source": {
      "name": "Smart Quiz fixtures (original)",
      "license": "original",
      "fetchedAt": "2026-06-21"
    },
    "durationMinutes": 35,
    "sections": [
      {
        "type": "vocab",
        "title": "語彙 (Từ vựng)",
        "instructions": "Chọn đáp án đúng.",
        "questions": [
          {
            "id": "n4-fixture-1-s1-q1",
            "prompt": "「べんり」 の いみ に ちかい もの は どれ ですか。",
            "options": [
              "tiện lợi",
              "nguy hiểm",
              "yên tĩnh",
              "phức tạp"
            ],
            "answerIndex": 0,
            "explanation": "べんり = tiện lợi."
          },
          {
            "id": "n4-fixture-1-s1-q2",
            "prompt": "この まち は とても ____ です。",
            "options": [
              "しずか",
              "たかい でんわ",
              "あおい",
              "はやく"
            ],
            "answerIndex": 0,
            "explanation": "しずか(な) = yên tĩnh, hợp với まち."
          }
        ]
      },
      {
        "type": "grammar",
        "title": "文法 (Ngữ pháp)",
        "instructions": "Chọn từ điền vào chỗ trống.",
        "questions": [
          {
            "id": "n4-fixture-1-s2-q1",
            "prompt": "あめ が ふって いる ____、しあい は ちゅうし です。",
            "options": [
              "ので",
              "のに",
              "でも",
              "まで"
            ],
            "answerIndex": 0,
            "explanation": "ので chỉ lý do: \"Vì trời mưa nên hoãn trận đấu\"."
          },
          {
            "id": "n4-fixture-1-s2-q2",
            "prompt": "にほんご を はなす こと ____ できます。",
            "options": [
              "が",
              "を",
              "に",
              "で"
            ],
            "answerIndex": 0,
            "explanation": "こと が できる: \"có thể nói tiếng Nhật\"."
          }
        ]
      },
      {
        "type": "reading",
        "title": "読解 (Đọc hiểu)",
        "instructions": "Đọc đoạn văn và trả lời.",
        "passages": [
          {
            "id": "n4-fixture-1-s3-p1",
            "text": "わたし の しゅみ は りょこう です。きょねん は ともだち と かんこく へ いきました。ことし は ひとり で たいわん に いく つもり です。",
            "translation": "Sở thích của tôi là du lịch. Năm ngoái tôi đi Hàn Quốc với bạn. Năm nay tôi định đi Đài Loan một mình."
          }
        ],
        "questions": [
          {
            "id": "n4-fixture-1-s3-q1",
            "prompt": "きょねん どこ へ いきましたか。",
            "options": [
              "たいわん",
              "かんこく",
              "にほん",
              "ちゅうごく"
            ],
            "answerIndex": 1,
            "passageId": "n4-fixture-1-s3-p1",
            "explanation": "「きょねん は … かんこく へ いきました」."
          },
          {
            "id": "n4-fixture-1-s3-q2",
            "prompt": "ことし の よてい は どれ ですか。",
            "options": [
              "ともだち と かんこく",
              "ひとり で たいわん",
              "かぞく と にほん",
              "ひとり で かんこく"
            ],
            "answerIndex": 1,
            "passageId": "n4-fixture-1-s3-p1",
            "explanation": "「ことし は ひとり で たいわん に いく つもり」."
          }
        ]
      }
    ]
  },
  {
    "id": "n3-fixture-1",
    "level": "N3",
    "title": "N3 — Đề luyện mẫu A (fixture)",
    "source": {
      "name": "Smart Quiz fixtures (original)",
      "license": "original",
      "fetchedAt": "2026-06-21"
    },
    "durationMinutes": 40,
    "sections": [
      {
        "type": "vocab",
        "title": "語彙 (Từ vựng)",
        "instructions": "Chọn đáp án đúng.",
        "questions": [
          {
            "id": "n3-fixture-1-s1-q1",
            "prompt": "「えんりょ」 の いみ に ちかい もの は どれ ですか。",
            "options": [
              "khách sáo, ngại ngần",
              "vui mừng",
              "tức giận",
              "mệt mỏi"
            ],
            "answerIndex": 0,
            "explanation": "えんりょ = sự khách sáo, ngại ngần."
          },
          {
            "id": "n3-fixture-1-s1-q2",
            "prompt": "かれ は しごと に ____ な ひと です。",
            "options": [
              "まじめ",
              "だめ",
              "むだ",
              "らく"
            ],
            "answerIndex": 0,
            "explanation": "まじめ(な) = nghiêm túc."
          }
        ]
      },
      {
        "type": "grammar",
        "title": "文法 (Ngữ pháp)",
        "instructions": "Chọn từ điền vào chỗ trống.",
        "questions": [
          {
            "id": "n3-fixture-1-s2-q1",
            "prompt": "いそがしくて、ひるごはん を たべる ____ も なかった。",
            "options": [
              "ひま",
              "よてい",
              "つもり",
              "はず"
            ],
            "answerIndex": 0,
            "explanation": "～ひま も ない: \"bận đến mức không có thời gian ăn trưa\"."
          },
          {
            "id": "n3-fixture-1-s2-q2",
            "prompt": "せんせい が おっしゃった ____ に、しけん は らいしゅう です。",
            "options": [
              "とおり",
              "ばかり",
              "ながら",
              "うちに"
            ],
            "answerIndex": 0,
            "explanation": "～とおりに: \"đúng như thầy đã nói\"."
          }
        ]
      },
      {
        "type": "reading",
        "title": "読解 (Đọc hiểu)",
        "instructions": "Đọc đoạn văn và trả lời.",
        "passages": [
          {
            "id": "n3-fixture-1-s3-p1",
            "text": "さいきん、ざいたく きんむ を する ひと が ふえて きました。かいしゃ に いかなくても しごと が できる ので、じかん を じゆう に つかえます。しかし、いえ で は しゅうちゅう しにくい と いう ひと も います。",
            "translation": "Gần đây số người làm việc tại nhà tăng lên. Vì không cần đến công ty vẫn làm được việc nên có thể dùng thời gian tự do. Tuy nhiên cũng có người nói ở nhà khó tập trung."
          }
        ],
        "questions": [
          {
            "id": "n3-fixture-1-s3-q1",
            "prompt": "ざいたく きんむ の りてん は なん ですか。",
            "options": [
              "きゅうりょう が たかい",
              "じかん を じゆう に つかえる",
              "どうりょう に あえる",
              "しゅうちゅう できる"
            ],
            "answerIndex": 1,
            "passageId": "n3-fixture-1-s3-p1",
            "explanation": "「じかん を じゆう に つかえます」."
          },
          {
            "id": "n3-fixture-1-s3-q2",
            "prompt": "ざいたく きんむ の もんだいてん は どれ ですか。",
            "options": [
              "しごと が おおい",
              "いえ で しゅうちゅう しにくい",
              "つうきん が たいへん",
              "きゅうりょう が ひくい"
            ],
            "answerIndex": 1,
            "passageId": "n3-fixture-1-s3-p1",
            "explanation": "「いえ で は しゅうちゅう しにくい」."
          }
        ]
      }
    ]
  },
  {
    "id": "n2-fixture-1",
    "level": "N2",
    "title": "N2 — Đề luyện mẫu A (fixture)",
    "source": {
      "name": "Smart Quiz fixtures (original)",
      "license": "original",
      "fetchedAt": "2026-06-21"
    },
    "durationMinutes": 50,
    "sections": [
      {
        "type": "vocab",
        "title": "語彙 (Từ vựng)",
        "instructions": "Chọn đáp án đúng.",
        "questions": [
          {
            "id": "n2-fixture-1-s1-q1",
            "prompt": "「あいまい」 の いみ は どれ ですか。",
            "options": [
              "mơ hồ, không rõ ràng",
              "chính xác",
              "rộng rãi",
              "nhanh chóng"
            ],
            "answerIndex": 0,
            "explanation": "あいまい = mơ hồ, không rõ ràng."
          },
          {
            "id": "n2-fixture-1-s1-q2",
            "prompt": "けいき が かいふく した。「かいふく」 の いみ は どれ ですか。",
            "options": [
              "hồi phục",
              "suy thoái",
              "dừng lại",
              "biến mất"
            ],
            "answerIndex": 0,
            "explanation": "かいふく = hồi phục, phục hồi."
          }
        ]
      },
      {
        "type": "grammar",
        "title": "文法 (Ngữ pháp)",
        "instructions": "Chọn từ điền vào chỗ trống.",
        "questions": [
          {
            "id": "n2-fixture-1-s2-q1",
            "prompt": "けっか は どう ____、さいご まで がんばる つもり です。",
            "options": [
              "であれ",
              "として",
              "につき",
              "において"
            ],
            "answerIndex": 0,
            "explanation": "どう であれ: \"dù kết quả thế nào đi nữa\"."
          },
          {
            "id": "n2-fixture-1-s2-q2",
            "prompt": "この データ に ____、うりあげ は ぞうか して いる。",
            "options": [
              "よると",
              "たいして",
              "かわって",
              "くわえて"
            ],
            "answerIndex": 0,
            "explanation": "～に よると: \"theo dữ liệu này\"."
          }
        ]
      },
      {
        "type": "reading",
        "title": "読解 (Đọc hiểu)",
        "instructions": "Đọc đoạn văn và trả lời.",
        "passages": [
          {
            "id": "n2-fixture-1-s3-p1",
            "text": "げんだい しゃかい で は、じょうほう が あふれて いる。たいせつ なの は、おおく の じょうほう の なか から ひつよう な もの を えらびとる ちから だ。すべて を しんじる の で は なく、しゅってん を たしかめる しゅうかん を み に つけたい。",
            "translation": "Trong xã hội hiện đại, thông tin tràn ngập. Điều quan trọng là năng lực chọn lọc thứ cần thiết từ vô vàn thông tin. Thay vì tin tất cả, ta nên rèn thói quen kiểm chứng nguồn gốc."
          }
        ],
        "questions": [
          {
            "id": "n2-fixture-1-s3-q1",
            "prompt": "ひっしゃ が たいせつ だ と かんがえて いる の は どれ ですか。",
            "options": [
              "すべて の じょうほう を しんじる こと",
              "ひつよう な じょうほう を えらぶ ちから",
              "じょうほう を ふやす こと",
              "しゅってん を むしする こと"
            ],
            "answerIndex": 1,
            "passageId": "n2-fixture-1-s3-p1",
            "explanation": "「ひつよう な もの を えらびとる ちから だ」."
          },
          {
            "id": "n2-fixture-1-s3-q2",
            "prompt": "ひっしゃ が すすめて いる しゅうかん は どれ ですか。",
            "options": [
              "しゅってん を たしかめる",
              "すべて を あんき する",
              "じょうほう を むしする",
              "ともだち に きく"
            ],
            "answerIndex": 0,
            "passageId": "n2-fixture-1-s3-p1",
            "explanation": "「しゅってん を たしかめる しゅうかん」."
          }
        ]
      }
    ]
  },
  {
    "id": "n1-fixture-1",
    "level": "N1",
    "title": "N1 — Đề luyện mẫu A (fixture)",
    "source": {
      "name": "Smart Quiz fixtures (original)",
      "license": "original",
      "fetchedAt": "2026-06-21"
    },
    "durationMinutes": 60,
    "sections": [
      {
        "type": "vocab",
        "title": "語彙 (Từ vựng)",
        "instructions": "Chọn đáp án đúng.",
        "questions": [
          {
            "id": "n1-fixture-1-s1-q1",
            "prompt": "「ばくぜん」 と した ふあん。「ばくぜん」 の いみ は どれ ですか。",
            "options": [
              "mơ hồ, mông lung",
              "mãnh liệt",
              "cụ thể",
              "tạm thời"
            ],
            "answerIndex": 0,
            "explanation": "ばくぜん = mơ hồ, mông lung."
          },
          {
            "id": "n1-fixture-1-s1-q2",
            "prompt": "「いっかん」 して しゅちょう する。「いっかん」 の いみ に ちかい もの は どれ ですか。",
            "options": [
              "nhất quán",
              "mâu thuẫn",
              "do dự",
              "ngẫu nhiên"
            ],
            "answerIndex": 0,
            "explanation": "いっかん = nhất quán, trước sau như một."
          }
        ]
      },
      {
        "type": "grammar",
        "title": "文法 (Ngữ pháp)",
        "instructions": "Chọn từ điền vào chỗ trống.",
        "questions": [
          {
            "id": "n1-fixture-1-s2-q1",
            "prompt": "プロ の せんしゅ ____、この ていど の れんしゅう は とうぜん だ。",
            "options": [
              "ともなると",
              "をもって",
              "がてら",
              "そばから"
            ],
            "answerIndex": 0,
            "explanation": "～ともなると: \"khi đã là tuyển thủ chuyên nghiệp thì…\"."
          },
          {
            "id": "n1-fixture-1-s2-q2",
            "prompt": "かれ の どりょく ____、この せいこう は ありえなかった。",
            "options": [
              "なくして は",
              "をかわきりに",
              "ならでは",
              "とあって"
            ],
            "answerIndex": 0,
            "explanation": "～なくしては: \"nếu không có nỗ lực của anh ấy thì…\"."
          }
        ]
      },
      {
        "type": "reading",
        "title": "読解 (Đọc hiểu)",
        "instructions": "Đọc đoạn văn và trả lời.",
        "passages": [
          {
            "id": "n1-fixture-1-s3-p1",
            "text": "かがく ぎじゅつ の はってん は、われわれ の せいかつ を ひかく てき ゆたか に した いっぽう で、あらた な りんり てき かだい を つきつけて いる。ぎじゅつ そのもの に ぜんあく は なく、それ を どう もちいる か が とわれて いる の だ。",
            "translation": "Sự phát triển của khoa học kỹ thuật một mặt làm đời sống chúng ta tương đối sung túc, mặt khác lại đặt ra những vấn đề đạo đức mới. Bản thân kỹ thuật không có thiện ác; điều bị chất vấn là sử dụng nó như thế nào."
          }
        ],
        "questions": [
          {
            "id": "n1-fixture-1-s3-q1",
            "prompt": "ひっしゃ に よれば、とわれて いる の は なに か。",
            "options": [
              "ぎじゅつ の ぜんあく",
              "ぎじゅつ を どう もちいる か",
              "せいかつ の ゆたかさ",
              "かがく の しんぽ そくど"
            ],
            "answerIndex": 1,
            "passageId": "n1-fixture-1-s3-p1",
            "explanation": "「それ を どう もちいる か が とわれて いる」."
          },
          {
            "id": "n1-fixture-1-s3-q2",
            "prompt": "かがく ぎじゅつ の はってん に ついて、ひっしゃ の かんがえ に あう もの は どれ か。",
            "options": [
              "りてん だけ が ある",
              "けってん だけ が ある",
              "りてん も かだい も ある",
              "えいきょう は ない"
            ],
            "answerIndex": 2,
            "passageId": "n1-fixture-1-s3-p1",
            "explanation": "Văn bản nêu cả mặt lợi (sung túc) và vấn đề (đạo đức)."
          }
        ]
      }
    ]
  }
];
